app:
  name: "Better PC"

server:
  port: "8080"

mongoDb:
  url: "mongodb://localhost:27017"
  usersDbName: "users"
  usersDbCollection:
    - "users"
    - "roles"
  shopDbName: "shop"
  shopDbCollections:
    - "cpu"
    - "motherboard"
    - "ram"
    - "ssd"
    - "hdd"
    - "cooling"
    - "powersupply"
    - "gpu"
    - "housing"
    - "orders"

tokens:
  accessTokenTTL: 15 # minutes
  accessTokenSigningKey: "agjl#@$k5gag7-=ad[pfadpkadm32"
  refreshTokenTTL: 196 # hours
  refreshTokenSigningKey: "lfgSDFk^481&df1@_asdpogD25fE"