app:
  name: "Better PC"

server:
  port: "8080"

mongoDb:
  url: "mongodb://localhost:27017"
  usersDbName: "users"
  usersDbCollection:
    - "users"
    - "roles"
  shopDbName: "shop"
  shopDbCollections:
    - "cpu"
    - "motherboard"
    - "ram"
    - "ssd"
    - "hdd"
    - "cooling"
    - "powersupply"
    - "gpu"
    - "housing"
    - "orders"
    - "categories"

tokens:
  accessTokenTTL: 15 # minutes
  accessTokenSigningKey: "agjl#@$k5gag7-=ad[pfadpkadm32"
  refreshTokenTTL: 168 # hours
  refreshTokenSigningKey: "lfgSDFk^481&df1@_asdpogD25fE"

notifications:
  email: "betterpc@mail.ru"
  password: "YkrvYMZ8KgEnqqtyUtGG"
  smtpHost: "smtp.mail.ru"
  smtpPort: "587"

users:
  image: "/assets/icons/userdefault.png"
  verificationTokenTTL: 24 #hours
  roles:
    customerRole: "CUSTOMER"
    adminRole: "ADMIN"
    shopAssistantRole: "SHOP_ASSISTANT"