app:
  name: "Better PC"

server:
  url: "http://localhost:8080"
  port: "8080"

mongoDb:
  url: "mongodb+srv://betterPC:median1@cluster0.qtpqc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  usersDbName: "users"
  usersDbCollection:
    - "users"
    - "roles"
  shopDbName: "shop"
  shopDbCollections:
    - "cpu"
    - "motherboard"
    - "ram"
    - "ssd"
    - "hdd"
    - "cooling"
    - "powersupply"
    - "gpu"
    - "housing"
    - "orders"
    - "categories"

localCache:
  expirationTime: "10m"
  purgeTime: "15m"

tokens:
  accessTokenTTL: "15m"
  accessTokenSigningKey: "agjl#@$k5gag7-=ad[pfadpkadm32"
  refreshTokenTTL: "168h"
  refreshTokenSigningKey: "lfgSDFk^481&df1@_asdpogD25fE"
  verificationTokenTTL: "24h"

notifications:
  email: "betterpc@mail.ru"
  password: "YkrvYMZ8KgEnqqtyUtGG"
  smtpHost: "smtp.mail.ru"
  smtpPort: "587"

users:
  image: "/assets/icons/userdefault.png"
  roles:
    customerRole: "CUSTOMER"
    adminRole: "ADMIN"
    shopAssistantRole: "SHOP_ASSISTANT"