app:
  name: "Better PC"

server:
  url: "http://localhost:8080"
  port: "8080"

mongoDb:
  username: "<username>"
  password: "<password>"
  clusterAddress: "<cluster>.<addr>.mongodb.net"
  options: "retryWrites=true&w=majority&appName=<name>"

  usersDbName: "users"
  usersCollection:
    - "users"
    - "roles"

  shopDbName: "shop"
  ordersCollections: "orders"
  productsCollectionList:
    - "cpu"
    - "motherboard"
    - "ram"
    - "ssd"
    - "hdd"
    - "cooling"
    - "powersupply"
    - "gpu"
    - "housing"
    - "orders"
    - "categories"

localCache:
  expirationTime: "10m"
  purgeTime: "15m"

tokens:
  accessTokenTTL: "15m"
  accessTokenSigningKey: "<accessTokenKey>"
  refreshTokenTTL: "168h"
  refreshTokenSigningKey: "<refreshTokenKey>"
  verificationTokenTTL: "24h"

notifications:
  email: "<emailAddress>"
  password: "<password>"
  smtpHost: "<smtp.host>"
  smtpPort: "<smtp.port>"

users:
  roles:
    customerRole: "CUSTOMER"
    adminRole: "ADMIN"
    shopAssistantRole: "SHOP_ASSISTANT"

stripe:
  publicKey: <public_key>
  privateKey: <private_key>